### ISSUE TITLE
Adding this code to the awsdocs code examples repo

### ISSUE THREAD

**Issue by Doug-AWS** [acm19/aws-request-signing-apache-interceptor#16] opened 2021-07-19 15:41 UTC
Would you folks be interested in adding your code to the [AWS SDK doc code examples repository](https://github.com/awsdocs/aws-doc-sdk-examples)?

**Comment by acm19** [comment] 2021-07-19 17:53
Hey @Doug-AWS, sure of course. Will you release the interceptor using SDK v2 as a library? https://github.com/amazon-archives/aws-request-signing-apache-interceptor/issues/2#issuecomment-623127099. I think people will benefit a lot from that. Is that your idea?

**Comment by Doug-AWS** [comment] 2021-07-19 19:25
We don't typically create libraries from our code examples. We usually show bits and pieces of the code in a guide doc, and then provide a link to the complete code. We could provide instructions for people who want to use it as a library.

We can work with you to create a PR for our repo if you like.

**Comment by acm19** [comment] 2021-07-19 21:37
Sure, just explain me what have in mind for the documentation and I'll be happy to create a PR.

Although, I still think interceptor is a nice library, there used to be an AWS lib for version 1 (which is where I get the original code from) that was quite useful when connecting to Elasticsearch, etc. Specially from things like lambdas where you want to use a lightweight connection with proper signature, otherwise people would have to copy and paste the code.

**Comment by Doug-AWS** [comment] 2021-07-20 13:01
Let me talk to the awsdocs folks and see if I can't create an essentially empty repo under our organization where you could drop all of your code as a PR, leaving it as a library. Then one of us could tag your code so we can replace the old library code with your code. Does that sound reasonable? We'll give you attribution for your hard work, so I'll probably pester you for some bio info for you and anyone else you want.

**Comment by acm19** [comment] 2021-07-20 17:19
Yeah, sounds perfect. Just ping me when you have it sorted and I'll prepare the PR, we could also later add something to the docs with some usage example if you want.

**Comment by Doug-AWS** [comment] 2021-07-20 21:24
I've got a new repo, but it's private until I switch to public. I'll start out with your code, so once I make it public I'll put the link here so you can look at it and file a PR for anything you want to change. Please update the readme there so you get credit for your hard work.

**Comment by Doug-AWS** [comment] 2021-07-21 13:35
https://github.com/awsdocs/aws-request-signing-apache-interceptor is now public. Please take a look at the readme and file a PR if you want to change anything.

**Comment by acm19** [comment] 2021-07-21 13:44
That's great, thanks @Doug-AWS, I'll take a closer look by the end of the week when I finish something I'm working on and create a PR if necessary. Also if you make available as Maven package I could archive this repo. Anyway, I'll take a look and get back to you with any feedback.

**Comment by acm19** [comment] 2021-07-25 18:58
Hey Doug, I've create a small PR with some changes: https://github.com/awsdocs/aws-request-signing-apache-interceptor/pull/1, feel free to leave any comments or modify it as necessary. But I have a couple of additional comments I didn't want to include in the PR without discussing them with you first:
* Are you open publish it to, at least, GitHub packages? I see that there are 18 download from my repo: https://github.com/acm19?tab=packages&repo_name=aws-request-signing-apache-interceptor. Meaning it's useful for people, they are willing to download a package from a stranger in internet. Making people compile it and manage any update by copy and pasting would be very painful.
* Package and Maven GroupId need renaming but I was unsure what's best to use for this library given it's included in the documentation. I'm happy to make the change if you tell me what's best in this case.
* There were a couple of issues unresolved in the old version of the library, if you are open to publish the Maven artefact I'll be happy to try to reproduce them (see if they weren't solved by the SDK update) and fix them when I have some time. I haven't done so far because I created this for a personal project and was expecting AWS would provide such library at some point.
* Would you consider enabling renovate in that lib? It would be nice to get dependencies updates from time to time. It could be even monthly.

**Comment by sapka12** [comment] 2022-01-26 14:06
@Doug-AWS is there any plan to publish a package to a public maven repo?

**Comment by acm19** [comment] 2022-06-27 22:38
@dblock Sure feel free to create a PR. I'll try to find some time to add some automation to the repo. I initially forked it and added the SDKv2 support because I needed it for a personal project with the idea of merging it into the the original repo. But after this time I'm sure that's not gonna happen so I'm happy to take a closer look into how to make more usable for people in the meantime.

**Comment by dblock** [comment] 2022-07-05 19:52
Looks like https://github.com/awsdocs/aws-request-signing-apache-interceptor was similarly abandoned. I propose to close this issue, and opened https://github.com/awsdocs/aws-request-signing-apache-interceptor/issues/2 to archive it.

**Comment by dblock** [comment] 2022-07-05 19:59
> @Doug-AWS is there any plan to publish a package to a public maven repo?

https://github.com/acm19/aws-request-signing-apache-interceptor/issues/35 and #23

**Closed** 2022-07-05 21:42 UTC
